import AERIALTURN1 from './AERIALTURN1';
import AERIALTURN2 from './AERIALTURN2';
import AERIALTURN3 from './AERIALTURN3';
import AERIALTURN4 from './AERIALTURN4';
import AERIALTURN5 from './AERIALTURN5';
import ATTACKAIRB from './ATTACKAIRB';
import ATTACKAIRD from './ATTACKAIRD';
import ATTACKAIRF from './ATTACKAIRF';
import ATTACKAIRN from './ATTACKAIRN';
import ATTACKAIRU from './ATTACKAIRU';
import ATTACKDASH from './ATTACKDASH';
import CATCHATTACK from './CATCHATTACK';
import CLIFFATTACKQUICK from './CLIFFATTACKQUICK';
import CLIFFATTACKSLOW from './CLIFFATTACKSLOW';
import CLIFFESCAPEQUICK from './CLIFFESCAPEQUICK';
import CLIFFESCAPESLOW from './CLIFFESCAPESLOW';
import CLIFFGETUPQUICK from './CLIFFGETUPQUICK';
import CLIFFGETUPSLOW from './CLIFFGETUPSLOW';
import CLIFFJUMPQUICK from './CLIFFJUMPQUICK';
import CLIFFJUMPSLOW from './CLIFFJUMPSLOW';
import DOWNATTACK from './DOWNATTACK';
import DOWNSMASH from './DOWNSMASH';
import DOWNSPECIALAIR from './DOWNSPECIALAIR';
import DOWNSPECIALGROUND from './DOWNSPECIALGROUND';
import DOWNTILT from './DOWNTILT';
import FORWARDSMASH from './FORWARDSMASH';
import FORWARDTILT from './FORWARDTILT';
import FURAFURA from './FURAFURA';
import GRAB from './GRAB';
import JAB1 from './JAB1';
import JAB2 from './JAB2';
import JUMPAERIAL1 from './JUMPAERIAL1';
import JUMPAERIAL2 from './JUMPAERIAL2';
import JUMPAERIAL3 from './JUMPAERIAL3';
import JUMPAERIAL4 from './JUMPAERIAL4';
import JUMPAERIAL5 from './JUMPAERIAL5';
import JUMPAERIALB from './JUMPAERIALB';
import JUMPAERIALF from './JUMPAERIALF';
import NEUTRALSPECIALAIR from './NEUTRALSPECIALAIR';
import NEUTRALSPECIALGROUND from './NEUTRALSPECIALGROUND';
import NEUTRALSPECIALGROUNDTURN from './NEUTRALSPECIALGROUNDTURN';
import SIDESPECIALAIR from './SIDESPECIALAIR';
import SIDESPECIALGROUND from './SIDESPECIALGROUND';
import THROWBACK from './THROWBACK';
import THROWDOWN from './THROWDOWN';
import THROWFORWARD from './THROWFORWARD';
import THROWNFOXBACK from './THROWNFOXBACK';
import THROWNFOXDOWN from './THROWNFOXDOWN';
import THROWNFOXFORWARD from './THROWNFOXFORWARD';
import THROWNFOXUP from './THROWNFOXUP';
import THROWNMARTHBACK from './THROWNMARTHBACK';
import THROWNMARTHDOWN from './THROWNMARTHDOWN';
import THROWNMARTHFORWARD from './THROWNMARTHFORWARD';
import THROWNMARTHUP from './THROWNMARTHUP';
import THROWNPUFFBACK from './THROWNPUFFBACK';
import THROWNPUFFDOWN from './THROWNPUFFDOWN';
import THROWNPUFFFORWARD from './THROWNPUFFFORWARD';
import THROWNPUFFUP from './THROWNPUFFUP';
import THROWUP from './THROWUP';
import UPSMASH from './UPSMASH';
import UPSPECIAL from './UPSPECIAL';
import UPTILT from './UPTILT';
import THROWNFALCOUP from "characters/puff/moves/THROWNFALCOUP";
import THROWNFALCODOWN from "characters/puff/moves/THROWNFALCODOWN";
import THROWNFALCOBACK from "characters/puff/moves/THROWNFALCOBACK";
import THROWNFALCOFORWARD from "characters/puff/moves/THROWNFALCOFORWARD";
import APPEAL from "characters/puff/moves/APPEAL";


export default {
  AERIALTURN1,
  AERIALTURN2,
  AERIALTURN3,
  AERIALTURN4,
  AERIALTURN5,
  ATTACKAIRB,
  ATTACKAIRD,
  ATTACKAIRF,
  ATTACKAIRN,
  ATTACKAIRU,
  ATTACKDASH,
  CATCHATTACK,
  CLIFFATTACKQUICK,
  CLIFFATTACKSLOW,
  CLIFFESCAPEQUICK,
  CLIFFESCAPESLOW,
  CLIFFGETUPQUICK,
  CLIFFGETUPSLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  DOWNATTACK,
  DOWNSMASH,
  DOWNSPECIALAIR,
  DOWNSPECIALGROUND,
  DOWNTILT,
  FORWARDSMASH,
  FORWARDTILT,
  FURAFURA,
  GRAB,
  JAB1,
  JAB2,
  JUMPAERIAL1,
  JUMPAERIAL2,
  JUMPAERIAL3,
  JUMPAERIAL4,
  JUMPAERIAL5,
  JUMPAERIALB,
  JUMPAERIALF,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  NEUTRALSPECIALGROUNDTURN,
  SIDESPECIALAIR,
  SIDESPECIALGROUND,
  THROWBACK,
  THROWDOWN,
  THROWFORWARD,
  THROWNFOXBACK,
  THROWNFOXDOWN,
  THROWNFOXFORWARD,
  THROWNFOXUP,
  THROWNMARTHBACK,
  THROWNMARTHDOWN,
  THROWNMARTHFORWARD,
  THROWNMARTHUP,
  THROWNPUFFBACK,
  THROWNPUFFDOWN,
  THROWNPUFFFORWARD,
  THROWNPUFFUP,
  THROWUP,
  UPSMASH,
  UPSPECIAL,
  UPTILT,
  THROWNFALCOUP,
  THROWNFALCODOWN,
  THROWNFALCOBACK,
  THROWNFALCOFORWARD,
  APPEAL
};