import AERIALTURN from "./AERIALTURN";
import AERIALTURN1 from "./AERIALTURN1";
import AERIALTURN2 from "./AERIALTURN2";
import AERIALTURN3 from "./AERIALTURN3";
import AERIALTURN4 from "./AERIALTURN4";
import ATTACKAIRB from "./ATTACKAIRB";
import ATTACKAIRD from "./ATTACKAIRD";
import ATTACKAIRF from "./ATTACKAIRF";
import ATTACKAIRN from "./ATTACKAIRN";
import ATTACKAIRU from "./ATTACKAIRU";
import ATTACKDASH from "./ATTACKDASH";
import CAPTURECUT from "./CAPTURECUT";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE";
import CAPTUREPULLED from "./CAPTUREPULLED";
import CAPTUREWAIT from "./CAPTUREWAIT";
import CATCHATTACK from "./CATCHATTACK";
import CATCHCUT from "./CATCHCUT";
import CATCHWAIT from "./CATCHWAIT";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW";
import CLIFFCATCH from "./CLIFFCATCH";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW";
import CLIFFWAIT from "./CLIFFWAIT";
import DAMAGEFALL from "./DAMAGEFALL";
import DAMAGEFLYHI from "./DAMAGEFLYHI";
import DAMAGEFLYLW from "./DAMAGEFLYLW";
import DAMAGEFLYN from "./DAMAGEFLYN";
import DAMAGEFLYTOP from "./DAMAGEFLYTOP";
import DAMAGEHI1 from "./DAMAGEHI1";
import DAMAGEHI2 from "./DAMAGEHI2";
import DAMAGEHI3 from "./DAMAGEHI3";
import DAMAGEN2 from "./DAMAGEN2";
import DASH from "./DASH";
import DEADDOWN from "./DEADDOWN";
import DEADLEFT from "./DEADLEFT";
import DEADRIGHT from "./DEADRIGHT";
import DEADUP from "./DEADUP";
import DOWNATTACK from "./DOWNATTACK";
import DOWNBOUND from "./DOWNBOUND";
import DOWNDAMAGE from "./DOWNDAMAGE";
import DOWNSMASH from "./DOWNSMASH";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND";
import DOWNSTANDB from "./DOWNSTANDB";
import DOWNSTANDF from "./DOWNSTANDF";
import DOWNSTANDN from "./DOWNSTANDN";
import DOWNTILT from "./DOWNTILT";
import DOWNWAIT from "./DOWNWAIT";
import ENTRANCE from "./ENTRANCE";
import ESCAPEAIR from "./ESCAPEAIR";
import ESCAPEB from "./ESCAPEB";
import ESCAPEF from "./ESCAPEF";
import ESCAPEN from "./ESCAPEN";
import FALL from "./FALL";
import FALLSPECIAL from "./FALLSPECIAL";
import FORWARDSMASH from "./FORWARDSMASH";
import FORWARDTILT from "./FORWARDTILT";
import FURASLEEPEND from "./FURASLEEPEND";
import FURASLEEPLOOP from "./FURASLEEPLOOP";
import FURASLEEPSTART from "./FURASLEEPSTART";
import GRAB from "./GRAB";
import GUARD from "./GUARD";
import GUARDOFF from "./GUARDOFF";
import GUARDON from "./GUARDON";
import JAB1 from "./JAB1";
import JAB2 from "./JAB2";
import JUMPAERIAL1 from "./JUMPAERIAL1";
import JUMPAERIAL2 from "./JUMPAERIAL2";
import JUMPAERIAL3 from "./JUMPAERIAL3";
import JUMPAERIAL4 from "./JUMPAERIAL4";
import JUMPAERIAL5 from "./JUMPAERIAL5";
import JUMPB from "./JUMPB";
import JUMPF from "./JUMPF";
import KNEEBEND from "./KNEEBEND";
import LANDING from "./LANDING";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL";
import MISSFOOT from "./MISSFOOT";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND";
import NEUTRALSPECIALGROUNDTURN from "./NEUTRALSPECIALGROUNDTURN";
import OTTOTTO from "./OTTOTTO";
import OTTOTTOWAIT from "./OTTOTTOWAIT";
import PASS from "./PASS";
import REBIRTH from "./REBIRTH";
import REBIRTHWAIT from "./REBIRTHWAIT";
import RUN from "./RUN";
import RUNBRAKE from "./RUNBRAKE";
import RUNTURN from "./RUNTURN";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL";
import SHIELDBREAKFLY from "./SHIELDBREAKFLY";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND";
import SIDESPECIALAIR from "./SIDESPECIALAIR";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND";
import SLEEP from "./SLEEP";
import SMASHTURN from "./SMASHTURN";
import SQUAT from "./SQUAT";
import SQUATRV from "./SQUATRV";
import SQUATWAIT from "./SQUATWAIT";
import STOPCEIL from "./STOPCEIL";
import TECHB from "./TECHB";
import TECHF from "./TECHF";
import TECHN from "./TECHN";
import TECHU from "./TECHU";
import THROWBACK from "./THROWBACK";
import THROWDOWN from "./THROWDOWN";
import THROWFORWARD from "./THROWFORWARD";
import THROWNFOXBACK from "./THROWNFOXBACK";
import THROWNFOXDOWN from "./THROWNFOXDOWN";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD";
import THROWNFOXUP from "./THROWNFOXUP";
import THROWNMARTHBACK from "./THROWNMARTHBACK";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN";
import THROWNMARTHFORWARD5 from "./THROWNMARTHFORWARD5";
import THROWNMARTHUP from "./THROWNMARTHUP";
import THROWNPUFFBACK from "./THROWNPUFFBACK";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD";
import THROWNPUFFUP from "./THROWNPUFFUP";
import THROWUP from "./THROWUP";
import TILTTURN from "./TILTTURN";
import UPSMASH from "./UPSMASH";
import UPSPECIAL from "./UPSPECIAL";
import UPTILT from "./UPTILT";
import WAIT from "./WAIT";
import WALK from "./WALK";
import WALKFAST from "./WALKFAST";
import WALKMIDDLE from "./WALKMIDDLE";
import WALKSLOW from "./WALKSLOW";
import WALLDAMAGE from "./WALLDAMAGE";
import WALLTECH from "./WALLTECH";
import WALLTECHJUMP from "./WALLTECHJUMP";


export default {
  AERIALTURN,
  AERIALTURN1,
  AERIALTURN2,
  AERIALTURN3,
  AERIALTURN4,
  ATTACKAIRB,
  ATTACKAIRD,
  ATTACKAIRF,
  ATTACKAIRN,
  ATTACKAIRU,
  ATTACKDASH,
  CAPTURECUT,
  CAPTUREDAMAGE,
  CAPTUREPULLED,
  CAPTUREWAIT,
  CATCHATTACK,
  CATCHCUT,
  CATCHWAIT,
  CLIFFATTACKQUICK,
  CLIFFATTACKSLOW,
  CLIFFCATCH,
  CLIFFESCAPEQUICK,
  CLIFFESCAPESLOW,
  CLIFFGETUPQUICK,
  CLIFFGETUPSLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  CLIFFWAIT,
  DAMAGEFALL,
  DAMAGEFLYHI,
  DAMAGEFLYLW,
  DAMAGEFLYN,
  DAMAGEFLYTOP,
  DAMAGEHI1,
  DAMAGEHI2,
  DAMAGEHI3,
  DAMAGEN2,
  DASH,
  DEADDOWN,
  DEADLEFT,
  DEADRIGHT,
  DEADUP,
  DOWNATTACK,
  DOWNBOUND,
  DOWNDAMAGE,
  DOWNSMASH,
  DOWNSPECIALAIR,
  DOWNSPECIALGROUND,
  DOWNSTANDB,
  DOWNSTANDF,
  DOWNSTANDN,
  DOWNTILT,
  DOWNWAIT,
  ENTRANCE,
  ESCAPEAIR,
  ESCAPEB,
  ESCAPEF,
  ESCAPEN,
  FALL,
  FALLSPECIAL,
  FORWARDSMASH,
  FORWARDTILT,
  FURASLEEPEND,
  FURASLEEPLOOP,
  FURASLEEPSTART,
  GRAB,
  GUARD,
  GUARDOFF,
  GUARDON,
  JAB1,
  JAB2,
  JUMPAERIAL1,
  JUMPAERIAL2,
  JUMPAERIAL3,
  JUMPAERIAL4,
  JUMPAERIAL5,
  JUMPB,
  JUMPF,
  KNEEBEND,
  LANDING,
  LANDINGATTACKAIRB,
  LANDINGATTACKAIRD,
  LANDINGATTACKAIRF,
  LANDINGATTACKAIRN,
  LANDINGATTACKAIRU,
  LANDINGFALLSPECIAL,
  MISSFOOT,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  NEUTRALSPECIALGROUNDTURN,
  OTTOTTO,
  OTTOTTOWAIT,
  PASS,
  REBIRTH,
  REBIRTHWAIT,
  RUN,
  RUNBRAKE,
  RUNTURN,
  SHIELDBREAKDOWNBOUND,
  SHIELDBREAKFALL,
  SHIELDBREAKFLY,
  SHIELDBREAKSTAND,
  SIDESPECIALAIR,
  SIDESPECIALGROUND,
  SLEEP,
  SMASHTURN,
  SQUAT,
  SQUATRV,
  SQUATWAIT,
  STOPCEIL,
  TECHB,
  TECHF,
  TECHN,
  TECHU,
  THROWBACK,
  THROWDOWN,
  THROWFORWARD,
  THROWNFOXBACK,
  THROWNFOXDOWN,
  THROWNFOXFORWARD,
  THROWNFOXUP,
  THROWNMARTHBACK,
  THROWNMARTHDOWN,
  THROWNMARTHFORWARD5,
  THROWNMARTHUP,
  THROWNPUFFBACK,
  THROWNPUFFDOWN,
  THROWNPUFFFORWARD,
  THROWNPUFFUP,
  THROWUP,
  TILTTURN,
  UPSMASH,
  UPSPECIAL,
  UPTILT,
  WAIT,
  WALK,
  WALKFAST,
  WALKMIDDLE,
  WALKSLOW,
  WALLDAMAGE,
  WALLTECH,
  WALLTECHJUMP,
};
