var AERIALTURN1 = require("./AERIALTURN1");
var CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW");
var DOWNSTANDB = require("./DOWNSTANDB");
var JUMPAERIAL2 = require("./JUMPAERIAL2");
var RUNBRAKE = require("./RUNBRAKE");
var THROWNFOXUP = require("./THROWNFOXUP");
var AERIALTURN2 = require("./AERIALTURN2");
var CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK");
var DOWNSTANDF = require("./DOWNSTANDF");
var JUMPAERIAL3 = require("./JUMPAERIAL3");
var RUNTURN = require("./RUNTURN");
var THROWNMARTHBACK = require("./THROWNMARTHBACK");
var AERIALTURN3 = require("./AERIALTURN3");
var CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW");
var DOWNSTANDN = require("./DOWNSTANDN");
var JUMPAERIAL4 = require("./JUMPAERIAL4");
var SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND");
var THROWNMARTHDOWN = require("./THROWNMARTHDOWN");
var AERIALTURN4 = require("./AERIALTURN4");
var CLIFFWAIT = require("./CLIFFWAIT");
var DOWNTILT = require("./DOWNTILT");
var JUMPAERIAL5 = require("./JUMPAERIAL5");
var SHIELDBREAKFALL = require("./SHIELDBREAKFALL");
var THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD");
var AERIALTURN5 = require("./AERIALTURN5");
var DAMAGEFALL = require("./DAMAGEFALL");
var DOWNWAIT = require("./DOWNWAIT");
var JUMPB = require("./JUMPB");
var SHIELDBREAKFLY = require("./SHIELDBREAKFLY");
var THROWNMARTHUP = require("./THROWNMARTHUP");
var ATTACKAIRB = require("./ATTACKAIRB");
var DAMAGEFLYHI = require("./DAMAGEFLYHI");
var ENTRANCE = require("./ENTRANCE");
var JUMPF = require("./JUMPF");
var SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND");
var THROWNPUFFBACK = require("./THROWNPUFFBACK");
var ATTACKAIRD = require("./ATTACKAIRD");
var DAMAGEFLYLW = require("./DAMAGEFLYLW");
var ESCAPEAIR = require("./ESCAPEAIR");
var KNEEBEND = require("./KNEEBEND");
var SIDESPECIALAIR = require("./SIDESPECIALAIR");
var THROWNPUFFDOWN = require("./THROWNPUFFDOWN");
var ATTACKAIRF = require("./ATTACKAIRF");
var DAMAGEFLYN = require("./DAMAGEFLYN");
var ESCAPEB = require("./ESCAPEB");
var LANDING = require("./LANDING");
var SIDESPECIALGROUND = require("./SIDESPECIALGROUND");
var THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD");
var ATTACKAIRN = require("./ATTACKAIRN");
var DAMAGEFLYTOP = require("./DAMAGEFLYTOP");
var ESCAPEF = require("./ESCAPEF");
var LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB");
var SLEEP = require("./SLEEP");
var THROWNPUFFUP = require("./THROWNPUFFUP");
var ATTACKAIRU = require("./ATTACKAIRU");
var DAMAGEHI1 = require("./DAMAGEHI1");
var ESCAPEN = require("./ESCAPEN");
var LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD");
var SMASHTURN = require("./SMASHTURN");
var THROWUP = require("./THROWUP");
var ATTACKDASH = require("./ATTACKDASH");
var DAMAGEHI2 = require("./DAMAGEHI2");
var FALL = require("./FALL");
var LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF");
var SQUAT = require("./SQUAT");
var TILTTURN = require("./TILTTURN");
var CAPTURECUT = require("./CAPTURECUT");
var DAMAGEHI3 = require("./DAMAGEHI3");
var FALLSPECIAL = require("./FALLSPECIAL");
var LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN");
var SQUATRV = require("./SQUATRV");
var UPSMASH = require("./UPSMASH");
var CAPTUREDAMAGE = require("./CAPTUREDAMAGE");
var DAMAGEN2 = require("./DAMAGEN2");
var FORWARDSMASH = require("./FORWARDSMASH");
var LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU");
var SQUATWAIT = require("./SQUATWAIT");
var UPSPECIAL = require("./UPSPECIAL");
var CAPTUREPULLED = require("./CAPTUREPULLED");
var DASH = require("./DASH");
var FORWARDTILT = require("./FORWARDTILT");
var LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL");
var STOPCEIL = require("./STOPCEIL");
var UPTILT = require("./UPTILT");
var CAPTUREWAIT = require("./CAPTUREWAIT");
var DEADDOWN = require("./DEADDOWN");
var FURASLEEPEND = require("./FURASLEEPEND");
var MISSFOOT = require("./MISSFOOT");
var TECHB = require("./TECHB");
var WAIT = require("./WAIT");
var CATCHATTACK = require("./CATCHATTACK");
var DEADLEFT = require("./DEADLEFT");
var FURASLEEPLOOP = require("./FURASLEEPLOOP");
var NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR");
var TECHF = require("./TECHF");
var WALK = require("./WALK");
var CATCHCUT = require("./CATCHCUT");
var DEADRIGHT = require("./DEADRIGHT");
var FURASLEEPSTART = require("./FURASLEEPSTART");
var NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND");
var TECHN = require("./TECHN");
var WALKFAST = require("./WALKFAST");
var CATCHWAIT = require("./CATCHWAIT");
var DEADUP = require("./DEADUP");
var GRAB = require("./GRAB");
var NEUTRALSPECIALGROUNDTURN = require("./NEUTRALSPECIALGROUNDTURN");
var TECHU = require("./TECHU");
var WALKMIDDLE = require("./WALKMIDDLE");
var CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK");
var DOWNATTACK = require("./DOWNATTACK");
var GUARD = require("./GUARD");
var OTTOTTO = require("./OTTOTTO");
var THROWBACK = require("./THROWBACK");
var WALKSLOW = require("./WALKSLOW");
var CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW");
var DOWNBOUND = require("./DOWNBOUND");
var GUARDOFF = require("./GUARDOFF");
var OTTOTTOWAIT = require("./OTTOTTOWAIT");
var THROWDOWN = require("./THROWDOWN");
var WALLDAMAGE = require("./WALLDAMAGE");
var CLIFFCATCH = require("./CLIFFCATCH");
var DOWNDAMAGE = require("./DOWNDAMAGE");
var GUARDON = require("./GUARDON");
var PASS = require("./PASS");
var THROWFORWARD = require("./THROWFORWARD");
var WALLTECH = require("./WALLTECH");
var CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK");
var DOWNSMASH = require("./DOWNSMASH");
var JAB1 = require("./JAB1");
var REBIRTH = require("./REBIRTH");
var THROWNFOXBACK = require("./THROWNFOXBACK");
var WALLTECHJUMP = require("./WALLTECHJUMP");
var CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW");
var DOWNSPECIALAIR = require("./DOWNSPECIALAIR");
var JAB2 = require("./JAB2");
var REBIRTHWAIT = require("./REBIRTHWAIT");
var THROWNFOXDOWN = require("./THROWNFOXDOWN");
var CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK");
var DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND");
var JUMPAERIAL1 = require("./JUMPAERIAL1");
var RUN = require("./RUN");
var THROWNFOXFORWARD = require("./THROWNFOXFORWARD");

module.exports = {
  AERIALTURN1: AERIALTURN1,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSTANDB: DOWNSTANDB,
  JUMPAERIAL2: JUMPAERIAL2,
  RUNBRAKE: RUNBRAKE,
  THROWNFOXUP: THROWNFOXUP,
  AERIALTURN2: AERIALTURN2,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDF: DOWNSTANDF,
  JUMPAERIAL3: JUMPAERIAL3,
  RUNTURN: RUNTURN,
  THROWNMARTHBACK: THROWNMARTHBACK,
  AERIALTURN3: AERIALTURN3,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDN: DOWNSTANDN,
  JUMPAERIAL4: JUMPAERIAL4,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  AERIALTURN4: AERIALTURN4,
  CLIFFWAIT: CLIFFWAIT,
  DOWNTILT: DOWNTILT,
  JUMPAERIAL5: JUMPAERIAL5,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  AERIALTURN5: AERIALTURN5,
  DAMAGEFALL: DAMAGEFALL,
  DOWNWAIT: DOWNWAIT,
  JUMPB: JUMPB,
  SHIELDBREAKFLY: SHIELDBREAKFLY,
  THROWNMARTHUP: THROWNMARTHUP,
  ATTACKAIRB: ATTACKAIRB,
  DAMAGEFLYHI: DAMAGEFLYHI,
  ENTRANCE: ENTRANCE,
  JUMPF: JUMPF,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNPUFFBACK: THROWNPUFFBACK,
  ATTACKAIRD: ATTACKAIRD,
  DAMAGEFLYLW: DAMAGEFLYLW,
  ESCAPEAIR: ESCAPEAIR,
  KNEEBEND: KNEEBEND,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  ATTACKAIRF: ATTACKAIRF,
  DAMAGEFLYN: DAMAGEFLYN,
  ESCAPEB: ESCAPEB,
  LANDING: LANDING,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  ATTACKAIRN: ATTACKAIRN,
  DAMAGEFLYTOP: DAMAGEFLYTOP,
  ESCAPEF: ESCAPEF,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  SLEEP: SLEEP,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRU: ATTACKAIRU,
  DAMAGEHI1: DAMAGEHI1,
  ESCAPEN: ESCAPEN,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SMASHTURN: SMASHTURN,
  THROWUP: THROWUP,
  ATTACKDASH: ATTACKDASH,
  DAMAGEHI2: DAMAGEHI2,
  FALL: FALL,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SQUAT: SQUAT,
  TILTTURN: TILTTURN,
  CAPTURECUT: CAPTURECUT,
  DAMAGEHI3: DAMAGEHI3,
  FALLSPECIAL: FALLSPECIAL,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SQUATRV: SQUATRV,
  UPSMASH: UPSMASH,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEN2: DAMAGEN2,
  FORWARDSMASH: FORWARDSMASH,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SQUATWAIT: SQUATWAIT,
  UPSPECIAL: UPSPECIAL,
  CAPTUREPULLED: CAPTUREPULLED,
  DASH: DASH,
  FORWARDTILT: FORWARDTILT,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  STOPCEIL: STOPCEIL,
  UPTILT: UPTILT,
  CAPTUREWAIT: CAPTUREWAIT,
  DEADDOWN: DEADDOWN,
  FURASLEEPEND: FURASLEEPEND,
  MISSFOOT: MISSFOOT,
  TECHB: TECHB,
  WAIT: WAIT,
  CATCHATTACK: CATCHATTACK,
  DEADLEFT: DEADLEFT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  TECHF: TECHF,
  WALK: WALK,
  CATCHCUT: CATCHCUT,
  DEADRIGHT: DEADRIGHT,
  FURASLEEPSTART: FURASLEEPSTART,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  TECHN: TECHN,
  WALKFAST: WALKFAST,
  CATCHWAIT: CATCHWAIT,
  DEADUP: DEADUP,
  GRAB: GRAB,
  NEUTRALSPECIALGROUNDTURN: NEUTRALSPECIALGROUNDTURN,
  TECHU: TECHU,
  WALKMIDDLE: WALKMIDDLE,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DOWNATTACK: DOWNATTACK,
  GUARD: GUARD,
  OTTOTTO: OTTOTTO,
  THROWBACK: THROWBACK,
  WALKSLOW: WALKSLOW,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNBOUND: DOWNBOUND,
  GUARDOFF: GUARDOFF,
  OTTOTTOWAIT: OTTOTTOWAIT,
  THROWDOWN: THROWDOWN,
  WALLDAMAGE: WALLDAMAGE,
  CLIFFCATCH: CLIFFCATCH,
  DOWNDAMAGE: DOWNDAMAGE,
  GUARDON: GUARDON,
  PASS: PASS,
  THROWFORWARD: THROWFORWARD,
  WALLTECH: WALLTECH,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNSMASH: DOWNSMASH,
  JAB1: JAB1,
  REBIRTH: REBIRTH,
  THROWNFOXBACK: THROWNFOXBACK,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  JAB2: JAB2,
  REBIRTHWAIT: REBIRTHWAIT,
  THROWNFOXDOWN: THROWNFOXDOWN,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  JUMPAERIAL1: JUMPAERIAL1,
  RUN: RUN,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
};
