var ATTACKAIRB = require("./ATTACKAIRB.js");
var CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW.js");
var DOWNSMASH = require("./DOWNSMASH.js");
var FALLSPECIAL = require("./FALLSPECIAL.js");
var JUMPB = require("./JUMPB.js");
var REBIRTHWAIT = require("./REBIRTHWAIT.js");
var TECHF = require("./TECHF.js");
var THROWNPUFFUP = require("./THROWNPUFFUP.js");
var ATTACKAIRD = require("./ATTACKAIRD.js");
var CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK.js");
var DOWNSPECIALAIRSTART = require("./DOWNSPECIALAIRSTART.js");
var DOWNSPECIALAIRLOOP = require("./DOWNSPECIALAIRLOOP.js");
var DOWNSPECIALAIREND = require("./DOWNSPECIALAIREND.js");
var DOWNSPECIALAIRTURN = require("./DOWNSPECIALAIRTURN.js");
var DOWNSPECIALAIRREFLECT = require("./DOWNSPECIALAIRREFLECT.js");
var FIREFOXBOUNCE = require("./FIREFOXBOUNCE.js");
var JUMPF = require("./JUMPF.js");
var REBOUND = require("./REBOUND.js");
var TECHN = require("./TECHN.js");
var THROWUP = require("./THROWUP.js");
var ATTACKAIRF = require("./ATTACKAIRF.js");
var CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW.js");
var DOWNSPECIALGROUNDSTART = require("./DOWNSPECIALGROUNDSTART.js");
var DOWNSPECIALGROUNDLOOP = require("./DOWNSPECIALGROUNDLOOP.js");
var DOWNSPECIALGROUNDEND = require("./DOWNSPECIALGROUNDEND.js");
var DOWNSPECIALGROUNDTURN = require("./DOWNSPECIALGROUNDTURN.js");
var DOWNSPECIALGROUNDREFLECT = require("./DOWNSPECIALGROUNDREFLECT.js");
var FORWARDSMASH = require("./FORWARDSMASH.js");
var KNEEBEND = require("./KNEEBEND.js");
var RUN = require("./RUN.js");
var TECHU = require("./TECHU.js");
var TILTTURN = require("./TILTTURN.js");
var ATTACKAIRN = require("./ATTACKAIRN.js");
var CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK.js");
var DOWNSTANDB = require("./DOWNSTANDB.js");
var FORWARDTILT = require("./FORWARDTILT.js");
var LANDING = require("./LANDING.js");
var RUNBRAKE = require("./RUNBRAKE.js");
var THROWBACK = require("./THROWBACK.js");
var UPSMASH = require("./UPSMASH.js");
var ATTACKAIRU = require("./ATTACKAIRU.js");
var CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW.js");
var DOWNSTANDF = require("./DOWNSTANDF.js");
var FURAFURA = require("./FURAFURA.js");
var LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB.js");
var RUNTURN = require("./RUNTURN.js");
var THROWDOWN = require("./THROWDOWN.js");
var UPSPECIALCHARGE = require("./UPSPECIALCHARGE.js");
var ATTACKDASH = require("./ATTACKDASH.js");
var CLIFFWAIT = require("./CLIFFWAIT.js");
var DOWNSTANDN = require("./DOWNSTANDN.js");
var FURASLEEPEND = require("./FURASLEEPEND.js");
var LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD.js");
var SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND.js");
var THROWFORWARD = require("./THROWFORWARD.js");
var UPSPECIALLAUNCH = require("./UPSPECIALLAUNCH.js");
var CAPTURECUT = require("./CAPTURECUT.js");
var DAMAGEFALL = require("./DAMAGEFALL.js");
var DOWNTILT = require("./DOWNTILT.js");
var FURASLEEPLOOP = require("./FURASLEEPLOOP.js");
var LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF.js");
var SHIELDBREAKFALL = require("./SHIELDBREAKFALL.js");
var THROWNFOXBACK = require("./THROWNFOXBACK.js");
var UPTILT = require("./UPTILT.js");
var CAPTUREDAMAGE = require("./CAPTUREDAMAGE.js");
var DAMAGEFLYN = require("./DAMAGEFLYN.js");
var DOWNWAIT = require("./DOWNWAIT.js");
var FURASLEEPSTART = require("./FURASLEEPSTART.js");
var LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN.js");
var SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND.js");
var THROWNFOXDOWN = require("./THROWNFOXDOWN.js");
var WAIT = require("./WAIT.js");
var CAPTUREPULLED = require("./CAPTUREPULLED.js");
var DAMAGEN2 = require("./DAMAGEN2.js");
var ENTRANCE = require("./ENTRANCE.js");
var GRAB = require("./GRAB.js");
var LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU.js");
var SIDESPECIALAIR = require("./SIDESPECIALAIR.js");
var THROWNFOXFORWARD = require("./THROWNFOXFORWARD.js");
var WALK = require("./WALK.js");
var CAPTUREWAIT = require("./CAPTUREWAIT.js");
var DASH = require("./DASH.js");
var ESCAPEAIR = require("./ESCAPEAIR.js");
var GUARD = require("./GUARD.js");
var LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL.js");
var SIDESPECIALGROUND = require("./SIDESPECIALGROUND.js");
var THROWNFOXUP = require("./THROWNFOXUP.js");
var WALLDAMAGE = require("./WALLDAMAGE.js");
var CATCHATTACK = require("./CATCHATTACK.js");
var DEADDOWN = require("./DEADDOWN.js");
var ESCAPEB = require("./ESCAPEB.js");
var GUARDOFF = require("./GUARDOFF.js");
var MISSFOOT = require("./MISSFOOT.js");
var SLEEP = require("./SLEEP.js");
var THROWNMARTHBACK = require("./THROWNMARTHBACK.js");
var WALLJUMP = require("./WALLJUMP.js");
var CATCHCUT = require("./CATCHCUT.js");
var DEADLEFT = require("./DEADLEFT.js");
var ESCAPEF = require("./ESCAPEF.js");
var GUARDON = require("./GUARDON.js");
var NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR.js");
var SMASHTURN = require("./SMASHTURN.js");
var THROWNMARTHDOWN = require("./THROWNMARTHDOWN.js");
var WALLTECH = require("./WALLTECH.js");
var CATCHWAIT = require("./CATCHWAIT.js");
var DEADRIGHT = require("./DEADRIGHT.js");
var ESCAPEN = require("./ESCAPEN.js");
var JAB1 = require("./JAB1.js");
var NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND.js");
var SQUAT = require("./SQUAT.js");
var THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD.js");
var WALLTECHJUMP = require("./WALLTECHJUMP.js");
var CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK.js");
var DEADUP = require("./DEADUP.js");
var JAB2 = require("./JAB2.js");
var OTTOTTO = require("./OTTOTTO.js");
var SQUATRV = require("./SQUATRV.js");
var THROWNMARTHUP = require("./THROWNMARTHUP.js");
var CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW.js");
var DOWNATTACK = require("./DOWNATTACK.js");
var JAB3 = require("./JAB3.js");
var OTTOTTOWAIT = require("./OTTOTTOWAIT.js");
var SQUATWAIT = require("./SQUATWAIT.js");
var THROWNPUFFBACK = require("./THROWNPUFFBACK.js");
var CLIFFCATCH = require("./CLIFFCATCH.js");
var DOWNBOUND = require("./DOWNBOUND.js");
var FALL = require("./FALL.js");
var JUMPAERIALB = require("./JUMPAERIALB.js");
var PASS = require("./PASS.js");
var STOPCEIL = require("./STOPCEIL.js");
var THROWNPUFFDOWN = require("./THROWNPUFFDOWN.js");
var CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK.js");
var DOWNDAMAGE = require("./DOWNDAMAGE.js");
var FALLAERIAL = require("./FALLAERIAL.js");
var JUMPAERIALF = require("./JUMPAERIALF.js");
var REBIRTH = require("./REBIRTH.js");
var TECHB = require("./TECHB.js");
var THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD.js");

module.exports = {
  ATTACKAIRB: ATTACKAIRB,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSMASH: DOWNSMASH,
  FALLSPECIAL: FALLSPECIAL,
  JUMPB: JUMPB,
  REBIRTHWAIT: REBIRTHWAIT,
  TECHF: TECHF,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRD: ATTACKAIRD,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALAIRSTART: DOWNSPECIALAIRSTART,
  DOWNSPECIALAIRLOOP: DOWNSPECIALAIRLOOP,
  DOWNSPECIALAIREND: DOWNSPECIALAIREND,
  DOWNSPECIALAIRTURN: DOWNSPECIALAIRTURN,
  DOWNSPECIALAIRREFLECT: DOWNSPECIALAIRREFLECT,
  FIREFOXBOUNCE: FIREFOXBOUNCE,
  JUMPF: JUMPF,
  REBOUND: REBOUND,
  TECHN: TECHN,
  THROWUP: THROWUP,
  ATTACKAIRF: ATTACKAIRF,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSPECIALGROUNDSTART: DOWNSPECIALGROUNDSTART,
  DOWNSPECIALGROUNDLOOP: DOWNSPECIALGROUNDLOOP,
  DOWNSPECIALGROUNDEND: DOWNSPECIALGROUNDEND,
  DOWNSPECIALGROUNDTURN: DOWNSPECIALGROUNDTURN,
  DOWNSPECIALGROUNDREFLECT: DOWNSPECIALGROUNDREFLECT,
  FORWARDSMASH: FORWARDSMASH,
  KNEEBEND: KNEEBEND,
  RUN: RUN,
  TECHU: TECHU,
  TILTTURN: TILTTURN,
  ATTACKAIRN: ATTACKAIRN,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDB: DOWNSTANDB,
  FORWARDTILT: FORWARDTILT,
  LANDING: LANDING,
  RUNBRAKE: RUNBRAKE,
  THROWBACK: THROWBACK,
  UPSMASH: UPSMASH,
  ATTACKAIRU: ATTACKAIRU,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDF: DOWNSTANDF,
  FURAFURA: FURAFURA,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  RUNTURN: RUNTURN,
  THROWDOWN: THROWDOWN,
  UPSPECIALCHARGE: UPSPECIALCHARGE,
  ATTACKDASH: ATTACKDASH,
  CLIFFWAIT: CLIFFWAIT,
  DOWNSTANDN: DOWNSTANDN,
  FURASLEEPEND: FURASLEEPEND,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWFORWARD: THROWFORWARD,
  UPSPECIALLAUNCH: UPSPECIALLAUNCH,
  CAPTURECUT: CAPTURECUT,
  DAMAGEFALL: DAMAGEFALL,
  DOWNTILT: DOWNTILT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNFOXBACK: THROWNFOXBACK,
  UPTILT: UPTILT,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEFLYN: DAMAGEFLYN,
  DOWNWAIT: DOWNWAIT,
  FURASLEEPSTART: FURASLEEPSTART,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNFOXDOWN: THROWNFOXDOWN,
  WAIT: WAIT,
  CAPTUREPULLED: CAPTUREPULLED,
  DAMAGEN2: DAMAGEN2,
  ENTRANCE: ENTRANCE,
  GRAB: GRAB,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  WALK: WALK,
  CAPTUREWAIT: CAPTUREWAIT,
  DASH: DASH,
  ESCAPEAIR: ESCAPEAIR,
  GUARD: GUARD,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNFOXUP: THROWNFOXUP,
  WALLDAMAGE: WALLDAMAGE,
  CATCHATTACK: CATCHATTACK,
  DEADDOWN: DEADDOWN,
  ESCAPEB: ESCAPEB,
  GUARDOFF: GUARDOFF,
  MISSFOOT: MISSFOOT,
  SLEEP: SLEEP,
  THROWNMARTHBACK: THROWNMARTHBACK,
  WALLJUMP: WALLJUMP,
  CATCHCUT: CATCHCUT,
  DEADLEFT: DEADLEFT,
  ESCAPEF: ESCAPEF,
  GUARDON: GUARDON,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  SMASHTURN: SMASHTURN,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  WALLTECH: WALLTECH,
  CATCHWAIT: CATCHWAIT,
  DEADRIGHT: DEADRIGHT,
  ESCAPEN: ESCAPEN,
  JAB1: JAB1,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  SQUAT: SQUAT,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DEADUP: DEADUP,
  JAB2: JAB2,
  OTTOTTO: OTTOTTO,
  SQUATRV: SQUATRV,
  THROWNMARTHUP: THROWNMARTHUP,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNATTACK: DOWNATTACK,
  JAB3: JAB3,
  OTTOTTOWAIT: OTTOTTOWAIT,
  SQUATWAIT: SQUATWAIT,
  THROWNPUFFBACK: THROWNPUFFBACK,
  CLIFFCATCH: CLIFFCATCH,
  DOWNBOUND: DOWNBOUND,
  FALL: FALL,
  JUMPAERIALB: JUMPAERIALB,
  PASS: PASS,
  STOPCEIL: STOPCEIL,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNDAMAGE: DOWNDAMAGE,
  FALLAERIAL: FALLAERIAL,
  JUMPAERIALF: JUMPAERIALF,
  REBIRTH: REBIRTH,
  TECHB: TECHB,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
};
