import ATTACKAIRB from "./ATTACKAIRB";
import ATTACKAIRD from "./ATTACKAIRD";
import ATTACKAIRF from "./ATTACKAIRF";
import ATTACKAIRN from "./ATTACKAIRN";
import ATTACKAIRU from "./ATTACKAIRU";
import ATTACKDASH from "./ATTACKDASH";
import CAPTURECUT from "./CAPTURECUT";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE";
import CAPTUREPULLED from "./CAPTUREPULLED";
import CAPTUREWAIT from "./CAPTUREWAIT";
import CATCHATTACK from "./CATCHATTACK";
import CATCHCUT from "./CATCHCUT";
import CATCHWAIT from "./CATCHWAIT";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW";
import CLIFFCATCH from "./CLIFFCATCH";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW";
import CLIFFWAIT from "./CLIFFWAIT";
import DAMAGEFALL from "./DAMAGEFALL";
import DAMAGEFLYN from "./DAMAGEFLYN";
import DAMAGEN2 from "./DAMAGEN2";
import DASH from "./DASH";
import DEADDOWN from "./DEADDOWN";
import DEADLEFT from "./DEADLEFT";
import DEADRIGHT from "./DEADRIGHT";
import DEADUP from "./DEADUP";
import DOWNATTACK from "./DOWNATTACK";
import DOWNBOUND from "./DOWNBOUND";
import DOWNDAMAGE from "./DOWNDAMAGE";
import DOWNSMASH from "./DOWNSMASH";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR";
import DOWNSPECIALAIR2 from "./DOWNSPECIALAIR2";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND";
import DOWNSPECIALGROUND2 from "./DOWNSPECIALGROUND2";
import DOWNSTANDB from "./DOWNSTANDB";
import DOWNSTANDF from "./DOWNSTANDF";
import DOWNSTANDN from "./DOWNSTANDN";
import DOWNTILT from "./DOWNTILT";
import DOWNWAIT from "./DOWNWAIT";
import ENTRANCE from "./ENTRANCE";
import ESCAPEAIR from "./ESCAPEAIR";
import ESCAPEB from "./ESCAPEB";
import ESCAPEF from "./ESCAPEF";
import ESCAPEN from "./ESCAPEN";
import FALL from "./FALL";
import FALLAERIAL from "./FALLAERIAL";
import FALLSPECIAL from "./FALLSPECIAL";
import FORWARDSMASH from "./FORWARDSMASH";
import FORWARDTILT from "./FORWARDTILT";
import FURAFURA from "./FURAFURA";
import FURASLEEPEND from "./FURASLEEPEND";
import FURASLEEPLOOP from "./FURASLEEPLOOP";
import FURASLEEPSTART from "./FURASLEEPSTART";
import GRAB from "./GRAB";
import GUARD from "./GUARD";
import GUARDOFF from "./GUARDOFF";
import GUARDON from "./GUARDON";
import JAB1 from "./JAB1";
import JAB2 from "./JAB2";
import JUMPAERIALB from "./JUMPAERIALB";
import JUMPAERIALF from "./JUMPAERIALF";
import JUMPB from "./JUMPB";
import JUMPF from "./JUMPF";
import KNEEBEND from "./KNEEBEND";
import LANDING from "./LANDING";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL";
import MISSFOOT from "./MISSFOOT";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND";
import OTTOTTO from "./OTTOTTO";
import OTTOTTOWAIT from "./OTTOTTOWAIT";
import PASS from "./PASS";
import REBIRTH from "./REBIRTH";
import REBIRTHWAIT from "./REBIRTHWAIT";
import REBOUND from "./REBOUND";
import RUN from "./RUN";
import RUNBRAKE from "./RUNBRAKE";
import RUNTURN from "./RUNTURN";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND";
import SIDESPECIALAIR from "./SIDESPECIALAIR";
import SIDESPECIALAIR2FORWARD from "./SIDESPECIALAIR2FORWARD";
import SIDESPECIALAIR2UP from "./SIDESPECIALAIR2UP";
import SIDESPECIALAIR3DOWN from "./SIDESPECIALAIR3DOWN";
import SIDESPECIALAIR3FORWARD from "./SIDESPECIALAIR3FORWARD";
import SIDESPECIALAIR3UP from "./SIDESPECIALAIR3UP";
import SIDESPECIALAIR4DOWN from "./SIDESPECIALAIR4DOWN";
import SIDESPECIALAIR4FORWARD from "./SIDESPECIALAIR4FORWARD";
import SIDESPECIALAIR4UP from "./SIDESPECIALAIR4UP";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND";
import SIDESPECIALGROUND2FORWARD from "./SIDESPECIALGROUND2FORWARD";
import SIDESPECIALGROUND2UP from "./SIDESPECIALGROUND2UP";
import SIDESPECIALGROUND3DOWN from "./SIDESPECIALGROUND3DOWN";
import SIDESPECIALGROUND3FORWARD from "./SIDESPECIALGROUND3FORWARD";
import SIDESPECIALGROUND3UP from "./SIDESPECIALGROUND3UP";
import SIDESPECIALGROUND4DOWN from "./SIDESPECIALGROUND4DOWN";
import SIDESPECIALGROUND4FORWARD from "./SIDESPECIALGROUND4FORWARD";
import SIDESPECIALGROUND4UP from "./SIDESPECIALGROUND4UP";
import SLEEP from "./SLEEP";
import SMASHTURN from "./SMASHTURN";
import SQUAT from "./SQUAT";
import SQUATRV from "./SQUATRV";
import SQUATWAIT from "./SQUATWAIT";
import STOPCEIL from "./STOPCEIL";
import TECHB from "./TECHB";
import TECHF from "./TECHF";
import TECHN from "./TECHN";
import TECHU from "./TECHU";
import THROWBACK from "./THROWBACK";
import THROWDOWN from "./THROWDOWN";
import THROWFORWARD from "./THROWFORWARD";
import THROWNFOXBACK from "./THROWNFOXBACK";
import THROWNFOXDOWN from "./THROWNFOXDOWN";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD";
import THROWNFOXUP from "./THROWNFOXUP";
import THROWNMARTHBACK from "./THROWNMARTHBACK";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD";
import THROWNMARTHUP from "./THROWNMARTHUP";
import THROWNPUFFBACK from "./THROWNPUFFBACK";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD";
import THROWNPUFFUP from "./THROWNPUFFUP";
import THROWUP from "./THROWUP";
import TILTTURN from "./TILTTURN";
import UPSMASH from "./UPSMASH";
import UPSPECIAL from "./UPSPECIAL";
import UPTILT from "./UPTILT";
import WAIT from "./WAIT";
import WALK from "./WALK";
import WALLDAMAGE from "./WALLDAMAGE";
import WALLJUMP from "./WALLJUMP";
import WALLTECH from "./WALLTECH";
import WALLTECHJUMP from "./WALLTECHJUMP";

export default {
  ATTACKAIRB,
  ATTACKAIRD,
  ATTACKAIRF,
  ATTACKAIRN,
  ATTACKAIRU,
  ATTACKDASH,
  CAPTURECUT,
  CAPTUREDAMAGE,
  CAPTUREPULLED,
  CAPTUREWAIT,
  CATCHATTACK,
  CATCHCUT,
  CATCHWAIT,
  CLIFFATTACKQUICK,
  CLIFFATTACKSLOW,
  CLIFFCATCH,
  CLIFFESCAPEQUICK,
  CLIFFESCAPESLOW,
  CLIFFGETUPQUICK,
  CLIFFGETUPSLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  CLIFFWAIT,
  DAMAGEFALL,
  DAMAGEFLYN,
  DAMAGEN2,
  DASH,
  DEADDOWN,
  DEADLEFT,
  DEADRIGHT,
  DEADUP,
  DOWNATTACK,
  DOWNBOUND,
  DOWNDAMAGE,
  DOWNSMASH,
  DOWNSPECIALAIR,
  DOWNSPECIALAIR2,
  DOWNSPECIALGROUND,
  DOWNSPECIALGROUND2,
  DOWNSTANDB,
  DOWNSTANDF,
  DOWNSTANDN,
  DOWNTILT,
  DOWNWAIT,
  ENTRANCE,
  ESCAPEAIR,
  ESCAPEB,
  ESCAPEF,
  ESCAPEN,
  FALL,
  FALLAERIAL,
  FALLSPECIAL,
  FORWARDSMASH,
  FORWARDTILT,
  FURAFURA,
  FURASLEEPEND,
  FURASLEEPLOOP,
  FURASLEEPSTART,
  GRAB,
  GUARD,
  GUARDOFF,
  GUARDON,
  JAB1,
  JAB2,
  JUMPAERIALB,
  JUMPAERIALF,
  JUMPB,
  JUMPF,
  KNEEBEND,
  LANDING,
  LANDINGATTACKAIRB,
  LANDINGATTACKAIRD,
  LANDINGATTACKAIRF,
  LANDINGATTACKAIRN,
  LANDINGATTACKAIRU,
  LANDINGFALLSPECIAL,
  MISSFOOT,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  OTTOTTO,
  OTTOTTOWAIT,
  PASS,
  REBIRTH,
  REBIRTHWAIT,
  REBOUND,
  RUN,
  RUNBRAKE,
  RUNTURN,
  SHIELDBREAKDOWNBOUND,
  SHIELDBREAKFALL,
  SHIELDBREAKSTAND,
  SIDESPECIALAIR,
  SIDESPECIALAIR2FORWARD,
  SIDESPECIALAIR2UP,
  SIDESPECIALAIR3DOWN,
  SIDESPECIALAIR3FORWARD,
  SIDESPECIALAIR3UP,
  SIDESPECIALAIR4DOWN,
  SIDESPECIALAIR4FORWARD,
  SIDESPECIALAIR4UP,
  SIDESPECIALGROUND,
  SIDESPECIALGROUND2FORWARD,
  SIDESPECIALGROUND2UP,
  SIDESPECIALGROUND3DOWN,
  SIDESPECIALGROUND3FORWARD,
  SIDESPECIALGROUND3UP,
  SIDESPECIALGROUND4DOWN,
  SIDESPECIALGROUND4FORWARD,
  SIDESPECIALGROUND4UP,
  SLEEP,
  SMASHTURN,
  SQUAT,
  SQUATRV,
  SQUATWAIT,
  STOPCEIL,
  TECHB,
  TECHF,
  TECHN,
  TECHU,
  THROWBACK,
  THROWDOWN,
  THROWFORWARD,
  THROWNFOXBACK,
  THROWNFOXDOWN,
  THROWNFOXFORWARD,
  THROWNFOXUP,
  THROWNMARTHBACK,
  THROWNMARTHDOWN,
  THROWNMARTHFORWARD,
  THROWNMARTHUP,
  THROWNPUFFBACK,
  THROWNPUFFDOWN,
  THROWNPUFFFORWARD,
  THROWNPUFFUP,
  THROWUP,
  TILTTURN,
  UPSMASH,
  UPSPECIAL,
  UPTILT,
  WAIT,
  WALK,
  WALLDAMAGE,
  WALLJUMP,
  WALLTECH,
  WALLTECHJUMP,
};
