import JAB1 from "./JAB1";
import JAB2 from "./JAB2";
import JAB3 from "./JAB3";
import DOWNTILT from "./DOWNTILT";
import UPTILT from "./UPTILT";
import FORWARDTILT from "./FORWARDTILT";
import FORWARDSMASH from "./FORWARDSMASH";
import UPSMASH from "./UPSMASH";
import DOWNSMASH from "./DOWNSMASH";
import ATTACKAIRF from "./ATTACKAIRF";
import ATTACKAIRB from "./ATTACKAIRB";
import ATTACKAIRU from "./ATTACKAIRU";
import ATTACKAIRD from "./ATTACKAIRD";
import ATTACKAIRN from "./ATTACKAIRN";
import ATTACKDASH from "./ATTACKDASH";
import UPSPECIAL from "./UPSPECIAL";
import UPSPECIALCHARGE from "./UPSPECIALCHARGE";
import UPSPECIALLAUNCH from "./UPSPECIALLAUNCH";
import FIREFOXBOUNCE from "./FIREFOXBOUNCE";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND";
import SIDESPECIALAIR from "./SIDESPECIALAIR";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND";
import THROWBACK from "./THROWBACK";
import THROWDOWN from "./THROWDOWN";
import THROWUP from "./THROWUP";
import THROWFORWARD from "./THROWFORWARD";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN";
import THROWNPUFFBACK from "./THROWNPUFFBACK";
import THROWNPUFFUP from "./THROWNPUFFUP";
import THROWNMARTHUP from "./THROWNMARTHUP";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN";
import THROWNMARTHBACK from "./THROWNMARTHBACK";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD";
import THROWNFOXUP from "./THROWNFOXUP";
import THROWNFOXDOWN from "./THROWNFOXDOWN";
import THROWNFOXBACK from "./THROWNFOXBACK";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK";
import DOWNATTACK from "./DOWNATTACK";
import GRAB from "./GRAB";
import CATCHATTACK from "./CATCHATTACK";

export default {
  JAB1,
  JAB2,
  JAB3,
  DOWNTILT,
  UPTILT,
  FORWARDTILT,
  FORWARDSMASH,
  UPSMASH,
  DOWNSMASH,
  ATTACKAIRF,
  ATTACKAIRB,
  ATTACKAIRU,
  ATTACKAIRD,
  ATTACKAIRN,
  ATTACKDASH,
  UPSPECIAL,
  UPSPECIALCHARGE,
  UPSPECIALLAUNCH,
  FIREFOXBOUNCE,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  SIDESPECIALAIR,
  SIDESPECIALGROUND,
  DOWNSPECIALAIR,
  DOWNSPECIALGROUND,
  THROWBACK,
  THROWDOWN,
  THROWUP,
  THROWFORWARD,
  THROWNPUFFFORWARD,
  THROWNPUFFDOWN,
  THROWNPUFFBACK,
  THROWNPUFFUP,
  THROWNMARTHUP,
  THROWNMARTHDOWN,
  THROWNMARTHBACK,
  THROWNMARTHFORWARD,
  THROWNFOXUP,
  THROWNFOXDOWN,
  THROWNFOXBACK,
  THROWNFOXFORWARD,
  CLIFFGETUPQUICK,
  CLIFFGETUPSLOW,
  CLIFFESCAPEQUICK,
  CLIFFESCAPESLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  CLIFFATTACKSLOW,
  CLIFFATTACKQUICK,
  DOWNATTACK,
  GRAB,
  CATCHATTACK,
};
