var CAPTUREDAMAGE = require("./CAPTUREDAMAGE");
var CAPTUREPULLED = require("./CAPTUREPULLED");
var CATCHATTACK = require("./CATCHATTACK");
var CLIFFCATCH = require("./CLIFFCATCH");
var DOWNDAMAGE = require("./DOWNDAMAGE");
var FALL = require("./FALL");
var FALLSPECIAL = require("./FALLSPECIAL");
var FALLAERIAL = require("./FALLAERIAL");
var GUARD = require("./GUARD");
var FURASLEEPLOOP = require("./FURASLEEPLOOP");
var KNEEBEND = require("./KNEEBEND");
var GUARDOFF = require("./GUARDOFF");
var GUARDON = require("./GUARDON");
var LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB");
var LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN");
var OTTOTTO = require("./OTTOTTO");
var SMASHTURN = require("./SMASHTURN");
var LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF");
var LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU");
var LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD");
var STOPCEIL = require("./STOPCEIL");
var REBOUND = require("./REBOUND");
var SQUATRV = require("./SQUATRV");
var SQUAT = require("./SQUAT");
var THROWNFALCONUP = require("./THROWNFALCONUP");
var THROWNFALCOBACK = require("./THROWNFALCOBACK");
var THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
var THROWNFALCOUP = require("./THROWNFALCOUP");
var THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
var THROWNMARTHBACK = require("./THROWNMARTHBACK");
var THROWNFALCONBACK = require("./THROWNFALCONBACK");
var THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD");
var THROWNFOXUP = require("./THROWNFOXUP");
var TILTTURN = require("./TILTTURN");
var THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD");
var THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD");
var THROWNPUFFUP = require("./THROWNPUFFUP");
var THROWNMARTHDOWN = require("./THROWNMARTHDOWN");
var THROWNFOXFORWARD = require("./THROWNFOXFORWARD");
var THROWNFOXBACK = require("./THROWNFOXBACK");
var THROWNSHEIKBACK = require("./THROWNSHEIKBACK");
var THROWNMARTHUP = require("./THROWNMARTHUP");
var ATTACKAIRD = require("./ATTACKAIRD");
var UPSPECIALCATCH = require("./UPSPECIALCATCH");
var ATTACKDASH = require("./ATTACKDASH");
var CAPTUREWAIT = require("./CAPTUREWAIT");
var CATCHCUT = require("./CATCHCUT");
var DASH = require("./DASH");
var DAMAGEN2 = require("./DAMAGEN2");
var DOWNSTANDN = require("./DOWNSTANDN");
var DOWNBOUND = require("./DOWNBOUND");
var DOWNSTANDF = require("./DOWNSTANDF");
var ESCAPEN = require("./ESCAPEN");
var JAB2 = require("./JAB2");
var THROWNSHEIKUP = require("./THROWNSHEIKUP");
var DOWNSPECIALAIRENDAIR = require("./DOWNSPECIALAIRENDAIR");
var ATTACKAIRF = require("./ATTACKAIRF");
var DOWNSPECIALAIR = require("./DOWNSPECIALAIR");
var DAMAGEFLYN = require("./DAMAGEFLYN");
var JAB3 = require("./JAB3");
var ATTACKAIRU = require("./ATTACKAIRU");
var ATTACKAIRB = require("./ATTACKAIRB");
var CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK");
var DOWNSPECIALGROUNDENDAIR = require("./DOWNSPECIALGROUNDENDAIR");
var CAPTURECUT = require("./CAPTURECUT");
var DOWNTILT = require("./DOWNTILT");
var CATCHWAIT = require("./CATCHWAIT");
var CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK");
var ESCAPEB = require("./ESCAPEB");
var ESCAPEF = require("./ESCAPEF");
var DOWNSTANDB = require("./DOWNSTANDB");
var DAMAGEFALL = require("./DAMAGEFALL");
var JUMPF = require("./JUMPF");
var JAB1 = require("./JAB1");
var FURASLEEPSTART = require("./FURASLEEPSTART");
var JUMPAERIALB = require("./JUMPAERIALB");
var FORWARDTILT = require("./FORWARDTILT");
var LANDING = require("./LANDING");
var MISSFOOT = require("./MISSFOOT");
var JUMPAERIALF = require("./JUMPAERIALF");
var GRAB = require("./GRAB");
var UPTILT = require("./UPTILT");
var THROWDOWN = require("./THROWDOWN");
var TECHU = require("./TECHU");
var TECHB = require("./TECHB");
var THROWFORWARD = require("./THROWFORWARD");
var WALK = require("./WALK");
var PASS = require("./PASS");
var WALLJUMP = require("./WALLJUMP");
var TECHN = require("./TECHN");
var TECHF = require("./TECHF");
var WALLTECH = require("./WALLTECH");
var RUN = require("./RUN");
var RUNBRAKE = require("./RUNBRAKE");
var WALLTECHJUMP = require("./WALLTECHJUMP");
var THROWNFALCODOWN = require("./THROWNFALCODOWN");
var RUNTURN = require("./RUNTURN");
var THROWNFOXDOWN = require("./THROWNFOXDOWN");
var THROWNSHEIKFORWARD = require("./THROWNSHEIKFORWARD");
var THROWNSHEIKDOWN = require("./THROWNSHEIKDOWN");
var THROWNPUFFBACK = require("./THROWNPUFFBACK");
var DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND");
var DOWNSPECIALGROUNDENDGROUND = require("./DOWNSPECIALGROUNDENDGROUND");
var ATTACKAIRN = require("./ATTACKAIRN");
var SIDESPECIALGROUNDHIT = require("./SIDESPECIALGROUNDHIT");
var CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK");
var CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK");
var CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW");
var CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW");
var DOWNATTACK = require("./DOWNATTACK");
var DOWNSMASH = require("./DOWNSMASH");
var DOWNWAIT = require("./DOWNWAIT");
var CLIFFWAIT = require("./CLIFFWAIT");
var ESCAPEAIR = require("./ESCAPEAIR");
var APPEAL = require("./APPEAL");
var FURASLEEPEND = require("./FURASLEEPEND");
var JUMPB = require("./JUMPB");
var DOWNSPECIALAIRENDGROUND = require("./DOWNSPECIALAIRENDGROUND");
var UPSMASH = require("./UPSMASH");
var THROWBACK = require("./THROWBACK");
var WALLDAMAGE = require("./WALLDAMAGE");
var THROWUP = require("./THROWUP");
var THROWNPUFFDOWN = require("./THROWNPUFFDOWN");
var CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW");
var CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW");
var FORWARDSMASH = require("./FORWARDSMASH");
var SIDESPECIALAIRHIT = require("./SIDESPECIALAIRHIT");
var WAIT = require("./WAIT");
var SQUATWAIT = require("./SQUATWAIT");
var SIDESPECIALGROUND = require("./SIDESPECIALGROUND");
var UPSPECIAL = require("./UPSPECIAL");
var UPSPECIALTHROW = require("./UPSPECIALTHROW");
var OTTOTTOWAIT = require("./OTTOTTOWAIT");
var SIDESPECIALAIR = require("./SIDESPECIALAIR");
var FURAFURA = require("./FURAFURA");
var NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND");
var NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR");
var ENTRANCE = require("./ENTRANCE");
var REBIRTH = require("./REBIRTH");
var REBIRTHWAIT = require("./REBIRTHWAIT");
var LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL");
var THROWNFALCONDIVE = require("./THROWNFALCONDIVE");
var SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND");
var SHIELDBREAKFALL = require("./SHIELDBREAKFALL");
var SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND");

module.exports = {
    CAPTUREDAMAGE: CAPTUREDAMAGE,
    CAPTUREPULLED: CAPTUREPULLED,
    CATCHATTACK: CATCHATTACK,
    CLIFFCATCH: CLIFFCATCH,
    DOWNDAMAGE: DOWNDAMAGE,
    FALL: FALL,
    FALLSPECIAL: FALLSPECIAL,
    FALLAERIAL: FALLAERIAL,
    GUARD: GUARD,
    FURASLEEPLOOP: FURASLEEPLOOP,
    KNEEBEND: KNEEBEND,
    GUARDOFF: GUARDOFF,
    GUARDON: GUARDON,
    LANDINGATTACKAIRB: LANDINGATTACKAIRB,
    LANDINGATTACKAIRN: LANDINGATTACKAIRN,
    OTTOTTO: OTTOTTO,
    SMASHTURN: SMASHTURN,
    LANDINGATTACKAIRF: LANDINGATTACKAIRF,
    LANDINGATTACKAIRU: LANDINGATTACKAIRU,
    LANDINGATTACKAIRD: LANDINGATTACKAIRD,
    STOPCEIL: STOPCEIL,
    REBOUND: REBOUND,
    SQUATRV: SQUATRV,
    SQUAT: SQUAT,
    THROWNFALCONUP: THROWNFALCONUP,
    THROWNFALCOBACK: THROWNFALCOBACK,
    THROWNFALCONDOWN: THROWNFALCONDOWN,
    THROWNFALCOUP: THROWNFALCOUP,
    THROWNFALCONFORWARD: THROWNFALCONFORWARD,
    THROWNMARTHBACK: THROWNMARTHBACK,
    THROWNFALCONBACK: THROWNFALCONBACK,
    THROWNFALCOFORWARD: THROWNFALCOFORWARD,
    THROWNFOXUP: THROWNFOXUP,
    TILTTURN: TILTTURN,
    THROWNMARTHFORWARD: THROWNMARTHFORWARD,
    THROWNPUFFFORWARD: THROWNPUFFFORWARD,
    THROWNPUFFUP: THROWNPUFFUP,
    THROWNMARTHDOWN: THROWNMARTHDOWN,
    THROWNFOXFORWARD: THROWNFOXFORWARD,
    THROWNFOXBACK: THROWNFOXBACK,
    THROWNSHEIKBACK: THROWNSHEIKBACK,
    THROWNMARTHUP: THROWNMARTHUP,
    ATTACKAIRD: ATTACKAIRD,
    UPSPECIALCATCH: UPSPECIALCATCH,
    ATTACKDASH: ATTACKDASH,
    CAPTUREWAIT: CAPTUREWAIT,
    CATCHCUT: CATCHCUT,
    DASH: DASH,
    DAMAGEN2: DAMAGEN2,
    DOWNSTANDN: DOWNSTANDN,
    DOWNBOUND: DOWNBOUND,
    DOWNSTANDF: DOWNSTANDF,
    ESCAPEN: ESCAPEN,
    JAB2: JAB2,
    THROWNSHEIKUP: THROWNSHEIKUP,
    DOWNSPECIALAIRENDAIR: DOWNSPECIALAIRENDAIR,
    ATTACKAIRF: ATTACKAIRF,
    DOWNSPECIALAIR: DOWNSPECIALAIR,
    DAMAGEFLYN: DAMAGEFLYN,
    JAB3: JAB3,
    ATTACKAIRU: ATTACKAIRU,
    ATTACKAIRB: ATTACKAIRB,
    CLIFFJUMPQUICK: CLIFFJUMPQUICK,
    DOWNSPECIALGROUNDENDAIR: DOWNSPECIALGROUNDENDAIR,
    CAPTURECUT: CAPTURECUT,
    DOWNTILT: DOWNTILT,
    CATCHWAIT: CATCHWAIT,
    CLIFFGETUPQUICK: CLIFFGETUPQUICK,
    ESCAPEB: ESCAPEB,
    ESCAPEF: ESCAPEF,
    DOWNSTANDB: DOWNSTANDB,
    DAMAGEFALL: DAMAGEFALL,
    JUMPF: JUMPF,
    JAB1: JAB1,
    FURASLEEPSTART: FURASLEEPSTART,
    JUMPAERIALB: JUMPAERIALB,
    FORWARDTILT: FORWARDTILT,
    LANDING: LANDING,
    MISSFOOT: MISSFOOT,
    JUMPAERIALF: JUMPAERIALF,
    GRAB: GRAB,
    UPTILT: UPTILT,
    THROWDOWN: THROWDOWN,
    TECHU: TECHU,
    TECHB: TECHB,
    THROWFORWARD: THROWFORWARD,
    WALK: WALK,
    PASS: PASS,
    WALLJUMP: WALLJUMP,
    TECHN: TECHN,
    TECHF: TECHF,
    WALLTECH: WALLTECH,
    RUN: RUN,
    RUNBRAKE: RUNBRAKE,
    WALLTECHJUMP: WALLTECHJUMP,
    THROWNFALCODOWN: THROWNFALCODOWN,
    RUNTURN: RUNTURN,
    THROWNFOXDOWN: THROWNFOXDOWN,
    THROWNSHEIKFORWARD: THROWNSHEIKFORWARD,
    THROWNSHEIKDOWN: THROWNSHEIKDOWN,
    THROWNPUFFBACK: THROWNPUFFBACK,
    DOWNSPECIALGROUND: DOWNSPECIALGROUND,
    DOWNSPECIALGROUNDENDGROUND: DOWNSPECIALGROUNDENDGROUND,
    ATTACKAIRN: ATTACKAIRN,
    SIDESPECIALGROUNDHIT: SIDESPECIALGROUNDHIT,
    CLIFFATTACKQUICK: CLIFFATTACKQUICK,
    CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
    CLIFFJUMPSLOW: CLIFFJUMPSLOW,
    CLIFFGETUPSLOW: CLIFFGETUPSLOW,
    DOWNATTACK: DOWNATTACK,
    DOWNSMASH: DOWNSMASH,
    DOWNWAIT: DOWNWAIT,
    CLIFFWAIT: CLIFFWAIT,
    ESCAPEAIR: ESCAPEAIR,
    APPEAL: APPEAL,
    FURASLEEPEND: FURASLEEPEND,
    JUMPB: JUMPB,
    DOWNSPECIALAIRENDGROUND: DOWNSPECIALAIRENDGROUND,
    UPSMASH: UPSMASH,
    THROWBACK: THROWBACK,
    WALLDAMAGE: WALLDAMAGE,
    THROWUP: THROWUP,
    THROWNPUFFDOWN: THROWNPUFFDOWN,
    CLIFFATTACKSLOW: CLIFFATTACKSLOW,
    CLIFFESCAPESLOW: CLIFFESCAPESLOW,
    FORWARDSMASH: FORWARDSMASH,
    SIDESPECIALAIRHIT: SIDESPECIALAIRHIT,
    WAIT: WAIT,
    SQUATWAIT: SQUATWAIT,
    SIDESPECIALGROUND: SIDESPECIALGROUND,
    UPSPECIAL: UPSPECIAL,
    UPSPECIALTHROW: UPSPECIALTHROW,
    OTTOTTOWAIT: OTTOTTOWAIT,
    SIDESPECIALAIR: SIDESPECIALAIR,
    FURAFURA: FURAFURA,
    NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
    NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
    ENTRANCE: ENTRANCE,
    REBIRTH: REBIRTH,
    REBIRTHWAIT: REBIRTHWAIT,
    LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
    THROWNFALCONDIVE: THROWNFALCONDIVE,
    SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
    SHIELDBREAKFALL: SHIELDBREAKFALL,
    SHIELDBREAKSTAND: SHIELDBREAKSTAND
}