import WAIT from "./WAIT";
import DASH from "./DASH";
import RUN from "./RUN";
import SMASHTURN from "./SMASHTURN";
import TILTTURN from "./TILTTURN";
import RUNBRAKE from "./RUNBRAKE";
import RUNTURN from "./RUNTURN";
import WALK from "./WALK";
import KNEEBEND from "./KNEEBEND";
import JUMPF from "./JUMPF";
import JUMPB from "./JUMPB";
import LANDING from "./LANDING";
import ESCAPEAIR from "./ESCAPEAIR";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL";
import FALL from "./FALL";
import FALLAERIAL from "./FALLAERIAL";
import FALLSPECIAL from "./FALLSPECIAL";
import SQUAT from "./SQUAT";
import SQUATWAIT from "./SQUATWAIT";
import SQUATRV from "./SQUATRV";
import JUMPAERIALF from "./JUMPAERIALF";
import JUMPAERIALB from "./JUMPAERIALB";
import PASS from "./PASS";
import GUARDON from "./GUARDON";
import GUARD from "./GUARD";
import GUARDOFF from "./GUARDOFF";
import CLIFFCATCH from "./CLIFFCATCH";
import CLIFFWAIT from "./CLIFFWAIT";
import DEADLEFT from "./DEADLEFT";
import DEADRIGHT from "./DEADRIGHT";
import DEADUP from "./DEADUP";
import DEADDOWN from "./DEADDOWN";
import REBIRTH from "./REBIRTH";
import REBIRTHWAIT from "./REBIRTHWAIT";
import DAMAGEFLYN from "./DAMAGEFLYN";
import DAMAGEFALL from "./DAMAGEFALL";
import DAMAGEN2 from "./DAMAGEN2";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU";
import ESCAPEB from "./ESCAPEB";
import ESCAPEF from "./ESCAPEF";
import ESCAPEN from "./ESCAPEN";
import DOWNBOUND from "./DOWNBOUND";
import DOWNWAIT from "./DOWNWAIT";
import DOWNDAMAGE from "./DOWNDAMAGE";
import DOWNSTANDN from "./DOWNSTANDN";
import DOWNSTANDB from "./DOWNSTANDB";
import DOWNSTANDF from "./DOWNSTANDF";
import TECHN from "./TECHN";
import TECHB from "./TECHB";
import TECHF from "./TECHF";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND";
import FURAFURA from "./FURAFURA";
import CAPTUREPULLED from "./CAPTUREPULLED";
import CAPTUREWAIT from "./CAPTUREWAIT";
import CATCHWAIT from "./CATCHWAIT";
import CAPTURECUT from "./CAPTURECUT";
import CATCHCUT from "./CATCHCUT";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE";
import WALLDAMAGE from "./WALLDAMAGE";
import WALLTECH from "./WALLTECH";
import WALLJUMP from "./WALLJUMP";
import WALLTECHJUMP from "./WALLTECHJUMP";
import OTTOTTO from "./OTTOTTO";
import OTTOTTOWAIT from "./OTTOTTOWAIT";
import MISSFOOT from "./MISSFOOT";
import FURASLEEPSTART from "./FURASLEEPSTART";
import FURASLEEPLOOP from "./FURASLEEPLOOP";
import FURASLEEPEND from "./FURASLEEPEND";
import STOPCEIL from "./STOPCEIL";
import TECHU from "./TECHU";
import SLEEP from "./SLEEP";
import ENTRANCE from "./ENTRANCE";

export default {
  WAIT,
  DASH,
  RUN,
  SMASHTURN,
  TILTTURN,
  RUNBRAKE,
  RUNTURN,
  WALK,
  KNEEBEND,
  JUMPF,
  JUMPB,
  LANDING,
  ESCAPEAIR,
  LANDINGFALLSPECIAL,
  FALL,
  FALLAERIAL,
  FALLSPECIAL,
  SQUAT,
  SQUATWAIT,
  SQUATRV,
  JUMPAERIALF,
  JUMPAERIALB,
  PASS,
  GUARDON,
  GUARD,
  GUARDOFF,
  CLIFFCATCH,
  CLIFFWAIT,
  DEADLEFT,
  DEADRIGHT,
  DEADUP,
  DEADDOWN,
  REBIRTH,
  REBIRTHWAIT,
  DAMAGEFLYN,
  DAMAGEFALL,
  DAMAGEN2,
  LANDINGATTACKAIRN,
  LANDINGATTACKAIRF,
  LANDINGATTACKAIRB,
  LANDINGATTACKAIRD,
  LANDINGATTACKAIRU,
  ESCAPEB,
  ESCAPEF,
  ESCAPEN,
  DOWNBOUND,
  DOWNWAIT,
  DOWNDAMAGE,
  DOWNSTANDN,
  DOWNSTANDB,
  DOWNSTANDF,
  TECHN,
  TECHB,
  TECHF,
  SHIELDBREAKFALL,
  SHIELDBREAKDOWNBOUND,
  SHIELDBREAKSTAND,
  FURAFURA,
  CAPTUREPULLED,
  CAPTUREWAIT,
  CATCHWAIT,
  CAPTURECUT,
  CATCHCUT,
  CAPTUREDAMAGE,
  WALLDAMAGE,
  WALLTECH,
  WALLJUMP,
  WALLTECHJUMP,
  OTTOTTO,
  OTTOTTOWAIT,
  MISSFOOT,
  FURASLEEPSTART,
  FURASLEEPLOOP,
  FURASLEEPEND,
  STOPCEIL,
  TECHU,
  SLEEP,
  ENTRANCE,
};
