// Libs
import "howler";
import $ from  "jquery";
window.$ = $;

// Legacy files
import "main/sfx.js";
import "settings.js";
import "characters/marth/ecbmarth.js";
import "characters/puff/ecbpuff.js";
import "characters/baseActionStates.js";
import "main/swordSwings.js";
import "main/vfx.js";
import "physics/hitDetection.js";
import "main/characters.js";
import "characters/marth/marthAttributes.js";
import "characters/puff/puffAttributes.js";
import "physics/article.js";
import "main/player.js";
import "physics/actionStateShortcuts.js";
import "characters/marth/marth.js";
import "characters/puff/puff.js";
import "characters/fox";
import "main/render.js";
import "menus/startup.js";
import "menus/startscreen.js";
import "menus/menu.js";
import "menus/audiomenu.js";
import "menus/gameplaymenu.js";
import "menus/keytest.js";
import "menus/keyboardmenu.js";
import "menus/credits.js";
import "menus/css.js";
import "target/targetbuilder.js";
import "target/targetplay.js";
import "menus/targetselect.js";
import "stages/stages.js";
import "stages/stagerender.js";
import "menus/stageselect.js";
import "physics/physics.js";
import "main/ai.js";
import "main/resize.js";
import "main/main.js";
