import ATTACKAIRB from "./ATTACKAIRB";
import ATTACKAIRD from "./ATTACKAIRD";
import ATTACKAIRF from "./ATTACKAIRF";
import ATTACKAIRN from "./ATTACKAIRN";
import ATTACKAIRU from "./ATTACKAIRU";
import ATTACKDASH from "./ATTACKDASH";
import CAPTURECUT from "./CAPTURECUT";
import CAPTUREDAMAGE from "./CAPTUREDAMAGE";
import CAPTUREPULLED from "./CAPTUREPULLED";
import CATCHATTACK from "./CATCHATTACK";
import CAPTUREWAIT from "./CAPTUREWAIT";
import CATCHCUT from "./CATCHCUT";
import CATCHWAIT from "./CATCHWAIT";
import CLIFFATTACKQUICK from "./CLIFFATTACKQUICK";
import CLIFFCATCH from "./CLIFFCATCH";
import CLIFFATTACKSLOW from "./CLIFFATTACKSLOW";
import CLIFFESCAPEQUICK from "./CLIFFESCAPEQUICK";
import CLIFFGETUPQUICK from "./CLIFFGETUPQUICK";
import CLIFFESCAPESLOW from "./CLIFFESCAPESLOW";
import CLIFFGETUPSLOW from "./CLIFFGETUPSLOW";
import CLIFFJUMPQUICK from "./CLIFFJUMPQUICK";
import CLIFFJUMPSLOW from "./CLIFFJUMPSLOW";
import CLIFFWAIT from "./CLIFFWAIT";
import DAMAGEFALL from "./DAMAGEFALL";
import DAMAGEFLYN from "./DAMAGEFLYN";
import DAMAGEN2 from "./DAMAGEN2";
import DASH from "./DASH";
import DOWNATTACK from "./DOWNATTACK";
import DOWNBOUND from "./DOWNBOUND";
import DOWNSMASH from "./DOWNSMASH";
import DOWNSPECIALAIR from "./DOWNSPECIALAIR";
import DOWNSPECIALGROUND from "./DOWNSPECIALGROUND";
import DOWNSTANDB from "./DOWNSTANDB";
import DOWNSTANDF from "./DOWNSTANDF";
import DOWNSTANDN from "./DOWNSTANDN";
import DOWNTILT from "./DOWNTILT";
import DOWNWAIT from "./DOWNWAIT";
import ESCAPEAIR from "./ESCAPEAIR";
import ESCAPEB from "./ESCAPEB";
import ESCAPEF from "./ESCAPEF";
import FALL from "./FALL";
import ESCAPEN from "./ESCAPEN";
import FALLAERIAL from "./FALLAERIAL";
import FALLSPECIAL from "./FALLSPECIAL";
import FORWARDSMASH from "./FORWARDSMASH";
import FORWARDTILT from "./FORWARDTILT";
import FURASLEEPEND from "./FURASLEEPEND";
import FURAFURA from "./FURAFURA";
import FURASLEEPSTART from "./FURASLEEPSTART";
import FURASLEEPLOOP from "./FURASLEEPLOOP";
import GUARD from "./GUARD";
import GRAB from "./GRAB";
import GUARDON from "./GUARDON";
import GUARDOFF from "./GUARDOFF";
import JAB1 from "./JAB1";
import JAB2 from "./JAB2";
import JAB3 from "./JAB3";
import KNEEBEND from "./KNEEBEND";
import JUMPAERIALB from "./JUMPAERIALB";
import JUMPAERIALF from "./JUMPAERIALF";
import JUMPF from "./JUMPF";
import JUMPB from "./JUMPB";
import LANDING from "./LANDING";
import LANDINGATTACKAIRB from "./LANDINGATTACKAIRB";
import LANDINGATTACKAIRD from "./LANDINGATTACKAIRD";
import LANDINGATTACKAIRF from "./LANDINGATTACKAIRF";
import LANDINGATTACKAIRN from "./LANDINGATTACKAIRN";
import LANDINGATTACKAIRU from "./LANDINGATTACKAIRU";
import MISSFOOT from "./MISSFOOT";
import NEUTRALSPECIALAIR from "./NEUTRALSPECIALAIR";
import NEUTRALSPECIALGROUND from "./NEUTRALSPECIALGROUND";
import PASS from "./PASS";
import REBOUND from "./REBOUND";
import RUN from "./RUN";
import RUNBRAKE from "./RUNBRAKE";
import RUNTURN from "./RUNTURN";
import SQUAT from "./SQUAT";
import SQUATRV from "./SQUATRV";
import STOPCEIL from "./STOPCEIL";
import TECHB from "./TECHB";
import TECHF from "./TECHF";
import TECHN from "./TECHN";
import SQUATWAIT from "./SQUATWAIT";
import TECHU from "./TECHU";
import THROWBACK from "./THROWBACK";
import THROWNFOXBACK from "./THROWNFOXBACK";
import THROWFORWARD from "./THROWFORWARD";
import THROWNFOXDOWN from "./THROWNFOXDOWN";
import THROWNFOXFORWARD from "./THROWNFOXFORWARD";
import THROWNFOXUP from "./THROWNFOXUP";
import THROWNMARTHBACK from "./THROWNMARTHBACK";
import THROWNMARTHDOWN from "./THROWNMARTHDOWN";
import THROWNMARTHFORWARD from "./THROWNMARTHFORWARD";
import THROWNMARTHUP from "./THROWNMARTHUP";
import THROWNPUFFBACK from "./THROWNPUFFBACK";
import THROWNPUFFFORWARD from "./THROWNPUFFFORWARD";
import THROWNPUFFUP from "./THROWNPUFFUP";
import THROWNPUFFDOWN from "./THROWNPUFFDOWN";
import TILTTURN from "./TILTTURN";
import THROWUP from "./THROWUP";
import UPSMASH from "./UPSMASH";
import UPTILT from "./UPTILT";
import UPSPECIALCHARGE from "./UPSPECIALCHARGE";
import UPSPECIALLAUNCH from "./UPSPECIALLAUNCH";
import WALK from "./WALK";
import WALLDAMAGE from "./WALLDAMAGE";
import WALLJUMP from "./WALLJUMP";
import WALLTECH from "./WALLTECH";
import WAIT from "./WAIT";
import SIDESPECIALAIR from "./SIDESPECIALAIR";
import SIDESPECIALGROUND from "./SIDESPECIALGROUND";
import FIREFOXBOUNCE from "./FIREFOXBOUNCE";
import DOWNDAMAGE from "./DOWNDAMAGE";
import OTTOTTO from "./OTTOTTO";
import OTTOTTOWAIT from "./OTTOTTOWAIT";
import DEADUP from "./DEADUP";
import DEADDOWN from "./DEADDOWN";
import DEADLEFT from "./DEADLEFT";
import DEADRIGHT from "./DEADRIGHT";
import ENTRANCE from "./ENTRANCE";
import SLEEP from "./SLEEP";
import REBIRTH from "./REBIRTH";
import REBIRTHWAIT from "./REBIRTHWAIT";
import LANDINGFALLSPECIAL from "./LANDINGFALLSPECIAL";
import SMASHTURN from "./SMASHTURN";
import SHIELDBREAKFALL from "./SHIELDBREAKFALL";
import SHIELDBREAKDOWNBOUND from "./SHIELDBREAKDOWNBOUND";
import SHIELDBREAKSTAND from "./SHIELDBREAKSTAND";
import WALLTECHJUMP from "./WALLTECHJUMP";
import THROWDOWN from "./THROWDOWN";
import FALCONDASH from "./FALCONDASH";
import FALCONKNEE from "./FALCONKNEE";

export default {
  ATTACKAIRB,
  ATTACKAIRD,
  ATTACKAIRF,
  ATTACKAIRN,
  ATTACKAIRU,
  ATTACKDASH,
  CAPTURECUT,
  CAPTUREDAMAGE,
  CAPTUREPULLED,
  CATCHATTACK,
  CAPTUREWAIT,
  CATCHCUT,
  CATCHWAIT,
  CLIFFATTACKQUICK,
  CLIFFCATCH,
  CLIFFATTACKSLOW,
  CLIFFESCAPEQUICK,
  CLIFFGETUPQUICK,
  CLIFFESCAPESLOW,
  CLIFFGETUPSLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  CLIFFWAIT,
  DAMAGEFALL,
  DAMAGEFLYN,
  DAMAGEN2,
  DASH,
  DOWNATTACK,
  DOWNBOUND,
  DOWNSMASH,
  DOWNSPECIALAIR,
  DOWNSPECIALGROUND,
  DOWNSTANDB,
  DOWNSTANDF,
  DOWNSTANDN,
  DOWNTILT,
  DOWNWAIT,
  ESCAPEAIR,
  ESCAPEB,
  ESCAPEF,
  FALL,
  ESCAPEN,
  FALLAERIAL,
  FALLSPECIAL,
  FORWARDSMASH,
  FORWARDTILT,
  FURASLEEPEND,
  FURAFURA,
  FURASLEEPSTART,
  FURASLEEPLOOP,
  GUARD,
  GRAB,
  GUARDON,
  GUARDOFF,
  JAB1,
  JAB2,
  JAB3,
  KNEEBEND,
  JUMPAERIALB,
  JUMPAERIALF,
  JUMPF,
  JUMPB,
  LANDING,
  LANDINGATTACKAIRB,
  LANDINGATTACKAIRD,
  LANDINGATTACKAIRF,
  LANDINGATTACKAIRN,
  LANDINGATTACKAIRU,
  MISSFOOT,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  PASS,
  REBOUND,
  RUN,
  RUNBRAKE,
  RUNTURN,
  SQUAT,
  SQUATRV,
  STOPCEIL,
  TECHB,
  TECHF,
  TECHN,
  SQUATWAIT,
  TECHU,
  THROWBACK,
  THROWNFOXBACK,
  THROWFORWARD,
  THROWNFOXDOWN,
  THROWNFOXFORWARD,
  THROWNFOXUP,
  THROWNMARTHBACK,
  THROWNMARTHDOWN,
  THROWNMARTHFORWARD,
  THROWNMARTHUP,
  THROWNPUFFBACK,
  THROWNPUFFFORWARD,
  THROWNPUFFUP,
  THROWNPUFFDOWN,
  TILTTURN,
  THROWUP,
  UPSMASH,
  UPTILT,
  UPSPECIALCHARGE,
  UPSPECIALLAUNCH,
  WALK,
  WALLDAMAGE,
  WALLJUMP,
  WALLTECH,
  WAIT,
  SIDESPECIALAIR,
  SIDESPECIALGROUND,
  FIREFOXBOUNCE,
  DOWNDAMAGE,
  OTTOTTO,
  OTTOTTOWAIT,
  DEADUP,
  DEADDOWN,
  DEADLEFT,
  DEADRIGHT,
  ENTRANCE,
  SLEEP,
  REBIRTH,
  REBIRTHWAIT,
  LANDINGFALLSPECIAL,
  SMASHTURN,
  SHIELDBREAKFALL,
  SHIELDBREAKDOWNBOUND,
  SHIELDBREAKSTAND,
  WALLTECHJUMP,
  THROWDOWN,
  FALCONDASH,
  FALCONKNEE,
};
